server:
  port: 8081
  servlet:
    context-path: /api

  springdoc:
    swagger-ui.path: /swagger-ui.html
    api-docs.path: /v3/api-docs
    packagesToScan: com.tulio.store_multimarcas
    show-actuator: true

jwt:
  private-key: classpath:keyprivate.pem
  public-key: classpath:keypublic.pem

spring:
  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      properties:
        request.timeout.ms: 30000
        delivery.timeout.ms: 45000
    properties:
      security.protocol: PLAINTEXT
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000

  logging:
    level:
      org.apache.kafka: WARN
      org.springframework.kafka: DEBUG